name: Upload Node.js 14 and 16 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        with:
          coverity_url: test.cov.com
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
